language: python
python:
  - "3.6"
install:
  - sudo apt-get update -y
  - sudo apt-get install -y lilypond
  - sudo apt-get install -y fluidsynth
  - pip install -r requirements.txt
  - python setup.py install
script:
  - nosetests unittest/
