language: python
python:
  - "3.6"
install:
  - sudo apt-get install lilypond
  - sudo apt-get install fluidsynth
  - pip install -r requirements.txt
  - python setup.py install
script:
  - nosetests unittest/
